spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/z77z?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456